//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 专辑类
    /// </summary>
    public partial class Album
    {
        public Album()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        /// <summary>
        /// 专辑编号
        /// </summary>
        public int AlbumId { get; set; }

        /// <summary>
        /// 专辑类型编号
        /// </summary>
        public int GenreId { get; set; }

        /// <summary>
        /// 艺术家编号
        /// </summary>
        public int ArtistId { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 价格
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// 专辑封面文件名
        /// </summary>
        public string AlbumArtUrl { get; set; }
    

        /// <summary>
        /// 艺术家对象
        /// </summary>
        public virtual Artist Artist { get; set; }
        /// <summary>
        /// 专辑类型对象
        /// </summary>
        public virtual Genre Genre { get; set; }
        /// <summary>
        /// 购物车集合
        /// </summary>
        public virtual ICollection<Cart> Carts { get; set; }
        /// <summary>
        /// 订单详情集合
        /// </summary>
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
