//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 专辑类型类
    /// </summary>
    public partial class Genre
    {
        public Genre()
        {
            this.Albums = new HashSet<Album>();
        }
    
        /// <summary>
        /// 编号
        /// </summary>
        public int GenreId { get; set; }

        /// <summary>
        /// 类型名称
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
    

        /// <summary>
        /// 专辑集合
        /// </summary>
        public virtual ICollection<Album> Albums { get; set; }
    }
}
